### ISSUE TITLE
Does it matter where GOPATH is set and when dep gains the ability to set its vendor directory at GOPATH/src root?

### ISSUE THREAD

**Issue by CMCDragonkai** [nixcloud/dep2nix#1]
Question in title.

**Comment by qknight** [comment]
`dep2nix` does not use the GOPATH at all. it only reads `Gopkgs.lock` and translates this into a `deps.nix`

**Comment by CMCDragonkai** [comment]
What happens if your project imports code from another directory that is relative to the GOPATH? And say maybe that other project also has a Gopkgs.lock?

On 25 February 2018 11:40:20 GMT+11:00, Joachim Schiele <notifications@github.com> wrote:
>dep2nix does not use the GOPATH at all. it only reads `Gopkgs.lock` and
>translates this into a deps.nix
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nixcloud/dep2nix/issues/1#issuecomment-368272512

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by qknight** [comment]
`dep2nix` uses the working directory where it is called from.
