### ISSUE TITLE
Hangs on 'hg' type repo.

### ISSUE THREAD

**Issue by domenkozar** [nixcloud/dep2nix#12]
To reproduce:

```
git clone https://github.com/DataDog/datadog-agent
cd datadog-agent
git checkout 155fddb3547919bd54530dfdb250e0cb2defae7d
dep2nix
```

It will hang on:

```
Found 124 projects to process.
* Processing: "bitbucket.org/ww/goautoneg"    
```

I think it's invoking ssh in the background (using git?), although it's a hg repo.

**Comment by qknight** [comment]
@domenkozar we could create a fallback for a failed `git clone` where we just try `hg`. 

@CrushedPixel do you want to implement that?

**Comment by CrushedPixel** [comment]
We shouldn't just use `hg` as a fallback - `dep` provides us with information about the VCS type of a dependency. I'll investigate.

**Comment by CrushedPixel** [comment]
Support for Mercurial repositories was added in 74cc4546fd0c09620089c5d474e73a85a852425a.

**Note that you need to have `mercurial` and `nix-prefetch-hg` installed on your nixos machine!**
If you don't have `mercurial`, it will just hang on the respective repository (this is an issue with `godep` which does not properly handle a missing `hg` command), and if you don't have  `nix-prefetch-hg` it won't be able to fetch the hash for the given dependency.

@qknight and I will soon force `mercurial` and `nix-prefetch-hg` as dependencies.

Please confirm if hg repositories now work for you and reopen the issue if needed!

**Comment by qknight** [comment]
@CrushedPixel please check https://github.com/nixcloud/dep2nix/commit/2dfae9e448abb6412d4747bc3d1f884ccf27357c and close if it works

**Comment by CrushedPixel** [comment]
Works with 383275fcb416e78669abab2b9ef2b1e158ba4e75.

**Comment by domenkozar** [comment]
It works, thank you so much? Could we release 0.2 to bump nixpkgs?

**Comment by qknight** [comment]
hihi, see https://github.com/nixcloud/dep2nix/releases ;-)
