### ISSUE TITLE
Poor handling of lots of projects

### ISSUE THREAD

**Issue by MostAwesomeDude** [nixcloud/dep2nix#14]
Many projects cause lots of temporary disk space to be used. However, on NixOS and many other distros, that is a tmpfs, and it can be quite limited in size. Upon filling the temporary disk, dep2nix issues a cryptic message and exits:

    error fetching project: Unable to get repository

Adding insult to injury, not only are Nix's git prefetcher directories left in the temporary disk, but so is the entirety of dep2nix's temporary directory, requiring a manual cleanup.

I experienced this while packaging [kubicorn](https://github.com/kubicorn/kubicorn) with a tmpfs of 1G. Remounting the tmpfs with 4G was sufficient to work around this problem, but also extravagant.

A possible fix would be to clean up each project incrementally, rather than deferring cleanup until the end.

Thanks for your hard work.

**Comment by CrushedPixel** [comment]
I addressed this in 1c9ea8cae43a9c644c83a95359e38196f787d196. Please let me know if you experience any more disk-space related issues.
