### ISSUE TITLE
Rename to godep2nix

### ISSUE THREAD

**Issue by lukateras** [nixcloud/dep2nix#6]
Hi! I would like to upstream this package to nixpkgs, because it's incredibly useful (thanks!), but the issue with that is that the name seems to be too generic.

**Comment by lukateras** [comment]
That said, given that it's the name of the tool that generates `Gopkgs.lock` files...

**Comment by qknight** [comment]
so should we rename it to `godep2nix` then?

but then all the blog posting links and so on won't work anymore so i would rather not do it.

**Comment by lukateras** [comment]
Yeah, sorry, this was a pretty bad idea.
