### ISSUE TITLE
Wrong sha error

### ISSUE THREAD

**Issue by nicknovitski** [nixcloud/dep2nix#8]
I think I've encountered and can reliably reproduce the error you mention in your readme with the project github.com/getsentry/raven-go, revision ed7bcb39ff10f39ab08e317ce16df282845852fa.  It stops after I download that revision with `nix-prefetch-git`.

Were you looking for reproductions?  If you've already figured out the problem, you can feel free to close the issue.

**Comment by CrushedPixel** [comment]
Is this related to #9? If so, please close :)

**Comment by nicknovitski** [comment]
I can't be certain, but I think it isn't: there's no constraint on the version of that package in my Gopkg.toml or .lock.

**Comment by qknight** [comment]
please provide an example where it does not work and reopen.
